### ISSUE TITLE
Can't put up an Item in the Market 1.18.2

### ISSUE THREAD

**Issue by NevendyND** [IAmSneak/diamond-auction-house#1]
Version: [diamondsauctionhouse-1.1.0.jar](https://www.curseforge.com/minecraft/mc-mods/diamond-auction-house/files/3817360)

This doesn't work with "/aucadd" (what i put in the config) or just "/auc"

I tried it if it works with "/auc add" but that doesn't work either.
Its not even asking me to hold an Item.

![image](https://user-images.githubusercontent.com/28860034/200206575-097f2ffe-c8b5-42fe-81bc-1df96c17c86e.png)

![image](https://user-images.githubusercontent.com/28860034/200206610-c33851d5-44e3-4710-b6c5-da1ac0250d54.png)

![image](https://user-images.githubusercontent.com/28860034/200206395-c3456c74-58bf-4b52-b576-3750ca6a1e1c.png)

**Comment by NevendyND** [comment]
I let this stay for Others if they have the same Problem in the Future.

Okay Nevermind i found the Solution in the Discord.

![image](https://user-images.githubusercontent.com/28860034/200207025-8451c353-a0f1-40d9-966f-c67495a6da3d.png)

**Comment by IAmSneak** [comment]
i should probably change "Name of the command" to "Name of the sub-command"
